site_name: Ziggy Pydust

repo_name: fulcrum-so/ziggy-pydust
repo_url: https://github.com/fulcrum-so/ziggy-pydust

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.indexes 
    #- navigation.tabs
    - navigation.expand
    - content.code.annotate

nav:
  - "index.md"
  - 'Getting Started': "getting_started.md"
  - 'User Guide':
    - "guide/index.md"
    - 'Modules': "guide/_1_modules.md"
    - 'Functions': "guide/_2_functions.md"
    - 'Classes': "guide/_3_classes.md"
    - 'Exceptions': "guide/exceptions.md"
    - 'Testing': "guide/_4_testing.md"
    - 'Memory Management': "guide/_5_memory.md"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fulcrum-so/ziggy-pydust
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fulcrum_so
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ziggy-pydust/
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

plugins:
- include-markdown
- mike

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables