site_name: Ziggy Pydust

repo_name: fulcrum-so/ziggy-pydust
repo_url: https://github.com/fulcrum-so/ziggy-pydust

theme:
  name: material
  palette:
    primary: deep orange
  features:
    - navigation.indexes 
    #- navigation.tabs


nav:
  - "index.md"
  - 'Getting Started': "getting_started.md"
  - 'User Guide':
    - "guide/index.md"
    - 'Python Modules': "guide/_1_modules.md"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fulcrum-so/ziggy-pydust
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ziggy-pydust/

plugins:
- include-markdown

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
  - pymdownx.snippets
  - pymdownx.superfences
  - tables